### ISSUE TITLE
Gerbers for front panel rev2b not working

### ISSUE THREAD

**Issue by da6353** [paulvee/VBA-Curve-Tracer#1]
Gerbers for front panel rev2b not working:

1.) board mfg unable to determine overall board size
2.) gerberviewer shows corrupt top/bottom layer, see attached images

![FrontPanelRev2b corrupt bottom layer gerber](https://user-images.githubusercontent.com/58539521/177880926-0f1fadf0-57df-4911-9cf7-51240c2ca7f0.PNG)
![FrontPanelRev2b corrupt top layer gerber](https://user-images.githubusercontent.com/58539521/177880929-b4809e1c-3987-4e66-ac4d-16f9d7e165c7.PNG)

**Comment by paulvee** [comment]
We order all the boards from PCBway. 

I just tried the Front panel and the Back panel with their viewer and another one and I have the same problem.
The Front board and the Main board are OK
We'll look into it and update the Github
